# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09d9b2c5d44718b16978a668601797383ed8610f6f1960368d1d33f587d294f23f83bb9ec4d7fa13266bba92aa7acc2e1b162d4c58fd7caf5357c4941c36fb29

test:
  secret_key_base: e08b09b8cf3c881ac171299792f2caecb0a95335ba5fb1ced9c1e2c5afbccc76443427f1f3ac7dcc8448690505f39f6428302c01826bcd9da353af926bb84d35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
